---
name: Docker Images

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v2

      - id: get_data
        uses: ./.github/actions/get-data

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: BORINGTUN_VERSION=v${{ steps.get_data.outputs.version }}
          tags: ${{ steps.get_data.outputs.tags }}
          push: true